openapi: 3.0.3
info:
  title: Django Sample REST API
  description: >-
    This is a sample API specification for a simple django API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8000
tags:
  - name: notes
    description: Notes
paths:
  /api/user/register/:
    summary: Register a user
    post:
      summary: Create a new user
      operationId: CreateNewUser
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid request body
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
  /api/token/:
    summary: Get a JWT token
    post:
      summary: Get JWT token
      operationId: Get JWT token
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid request body
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"


components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
          example: "my-username"
        password:
          type: string
          example: "my-password"
